### YamlMime:ManagedReference
items:
- uid: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper
  commentId: T:OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper
  id: RendererWorld.WorldUIRenderSettingsPopper
  parent: OnixRuntime.Api.Rendering
  children:
  - OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.#ctor(OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper,OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper,OnixRuntime.Api.Rendering.RendererWorld)
  - OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose
  langs:
  - csharp
  - vb
  name: RendererWorld.WorldUIRenderSettingsPopper
  nameWithType: RendererWorld.WorldUIRenderSettingsPopper
  fullName: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper
  type: Struct
  source:
    remote:
      path: OnixRuntime/Api/Rendering/RendererWorld.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: WorldUIRenderSettingsPopper
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/Rendering/RendererWorld.cs
    startLine: 59
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.Rendering
  summary: Helper struct for managing world UI render settings and transformation stack with automatic pop on dispose.
  example: []
  syntax:
    content: 'public struct RendererWorld.WorldUIRenderSettingsPopper : IDisposable'
    content.vb: Public Structure RendererWorld.WorldUIRenderSettingsPopper Implements IDisposable
  implements:
  - System.IDisposable
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.#ctor(OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper,OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper,OnixRuntime.Api.Rendering.RendererWorld)
  commentId: M:OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.#ctor(OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper,OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper,OnixRuntime.Api.Rendering.RendererWorld)
  id: '#ctor(OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper,OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper,OnixRuntime.Api.Rendering.RendererWorld)'
  parent: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper
  langs:
  - csharp
  - vb
  name: WorldUIRenderSettingsPopper(WorldRenderSettingsPopper, TransformationPopper, RendererWorld)
  nameWithType: RendererWorld.WorldUIRenderSettingsPopper.WorldUIRenderSettingsPopper(RendererWorld.WorldRenderSettingsPopper, RendererCommon.TransformationPopper, RendererWorld)
  fullName: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.WorldUIRenderSettingsPopper(OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper, OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper, OnixRuntime.Api.Rendering.RendererWorld)
  type: Constructor
  source:
    remote:
      path: OnixRuntime/Api/Rendering/RendererWorld.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: .ctor
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/Rendering/RendererWorld.cs
    startLine: 59
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.Rendering
  summary: Helper struct for managing world UI render settings and transformation stack with automatic pop on dispose.
  example: []
  syntax:
    content: public WorldUIRenderSettingsPopper(RendererWorld.WorldRenderSettingsPopper worldSettingsPopperCtor, RendererCommon.TransformationPopper transformationPopperCtor, RendererWorld renderer)
    parameters:
    - id: worldSettingsPopperCtor
      type: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper
    - id: transformationPopperCtor
      type: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper
    - id: renderer
      type: OnixRuntime.Api.Rendering.RendererWorld
    content.vb: Public Sub New(worldSettingsPopperCtor As RendererWorld.WorldRenderSettingsPopper, transformationPopperCtor As RendererCommon.TransformationPopper, renderer As RendererWorld)
  overload: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.#ctor*
  nameWithType.vb: RendererWorld.WorldUIRenderSettingsPopper.New(RendererWorld.WorldRenderSettingsPopper, RendererCommon.TransformationPopper, RendererWorld)
  fullName.vb: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.New(OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper, OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper, OnixRuntime.Api.Rendering.RendererWorld)
  name.vb: New(WorldRenderSettingsPopper, TransformationPopper, RendererWorld)
- uid: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose
  commentId: M:OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose
  id: Dispose
  parent: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper
  langs:
  - csharp
  - vb
  name: Dispose()
  nameWithType: RendererWorld.WorldUIRenderSettingsPopper.Dispose()
  fullName: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose()
  type: Method
  source:
    remote:
      path: OnixRuntime/Api/Rendering/RendererWorld.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: Dispose
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/Rendering/RendererWorld.cs
    startLine: 67
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.Rendering
  summary: Pops the world UI render settings and transformation when disposed.
  example: []
  syntax:
    content: public void Dispose()
    content.vb: Public Sub Dispose()
  overload: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose*
  implements:
  - System.IDisposable.Dispose
references:
- uid: OnixRuntime.Api.Rendering
  commentId: N:OnixRuntime.Api.Rendering
  href: OnixRuntime.html
  name: OnixRuntime.Api.Rendering
  nameWithType: OnixRuntime.Api.Rendering
  fullName: OnixRuntime.Api.Rendering
  spec.csharp:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Api
    name: Api
    href: OnixRuntime.Api.html
  - name: .
  - uid: OnixRuntime.Api.Rendering
    name: Rendering
    href: OnixRuntime.Api.Rendering.html
  spec.vb:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Api
    name: Api
    href: OnixRuntime.Api.html
  - name: .
  - uid: OnixRuntime.Api.Rendering
    name: Rendering
    href: OnixRuntime.Api.Rendering.html
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.#ctor*
  commentId: Overload:OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.#ctor
  href: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.html#OnixRuntime_Api_Rendering_RendererWorld_WorldUIRenderSettingsPopper__ctor_OnixRuntime_Api_Rendering_RendererWorld_WorldRenderSettingsPopper_OnixRuntime_Api_Rendering_RendererCommon_TransformationPopper_OnixRuntime_Api_Rendering_RendererWorld_
  name: WorldUIRenderSettingsPopper
  nameWithType: RendererWorld.WorldUIRenderSettingsPopper.WorldUIRenderSettingsPopper
  fullName: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.WorldUIRenderSettingsPopper
  nameWithType.vb: RendererWorld.WorldUIRenderSettingsPopper.New
  fullName.vb: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.New
  name.vb: New
- uid: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper
  commentId: T:OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper
  parent: OnixRuntime.Api.Rendering
  href: OnixRuntime.Api.Rendering.RendererWorld.html
  name: RendererWorld.WorldRenderSettingsPopper
  nameWithType: RendererWorld.WorldRenderSettingsPopper
  fullName: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper
  spec.csharp:
  - uid: OnixRuntime.Api.Rendering.RendererWorld
    name: RendererWorld
    href: OnixRuntime.Api.Rendering.RendererWorld.html
  - name: .
  - uid: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper
    name: WorldRenderSettingsPopper
    href: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper.html
  spec.vb:
  - uid: OnixRuntime.Api.Rendering.RendererWorld
    name: RendererWorld
    href: OnixRuntime.Api.Rendering.RendererWorld.html
  - name: .
  - uid: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper
    name: WorldRenderSettingsPopper
    href: OnixRuntime.Api.Rendering.RendererWorld.WorldRenderSettingsPopper.html
- uid: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper
  commentId: T:OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper
  parent: OnixRuntime.Api.Rendering
  href: OnixRuntime.Api.Rendering.RendererCommon.html
  name: RendererCommon.TransformationPopper
  nameWithType: RendererCommon.TransformationPopper
  fullName: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper
  spec.csharp:
  - uid: OnixRuntime.Api.Rendering.RendererCommon
    name: RendererCommon
    href: OnixRuntime.Api.Rendering.RendererCommon.html
  - name: .
  - uid: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper
    name: TransformationPopper
    href: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper.html
  spec.vb:
  - uid: OnixRuntime.Api.Rendering.RendererCommon
    name: RendererCommon
    href: OnixRuntime.Api.Rendering.RendererCommon.html
  - name: .
  - uid: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper
    name: TransformationPopper
    href: OnixRuntime.Api.Rendering.RendererCommon.TransformationPopper.html
- uid: OnixRuntime.Api.Rendering.RendererWorld
  commentId: T:OnixRuntime.Api.Rendering.RendererWorld
  parent: OnixRuntime.Api.Rendering
  href: OnixRuntime.Api.Rendering.RendererWorld.html
  name: RendererWorld
  nameWithType: RendererWorld
  fullName: OnixRuntime.Api.Rendering.RendererWorld
- uid: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose*
  commentId: Overload:OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose
  href: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.html#OnixRuntime_Api_Rendering_RendererWorld_WorldUIRenderSettingsPopper_Dispose
  name: Dispose
  nameWithType: RendererWorld.WorldUIRenderSettingsPopper.Dispose
  fullName: OnixRuntime.Api.Rendering.RendererWorld.WorldUIRenderSettingsPopper.Dispose
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
