### YamlMime:ManagedReference
items:
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  id: OnixSettingEnum.EnumEntry
  parent: OnixRuntime.Api.OnixClient.Settings
  children:
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.#ctor(System.Int32,System.String)
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As``1
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value
  langs:
  - csharp
  - vb
  name: OnixSettingEnum.EnumEntry
  nameWithType: OnixSettingEnum.EnumEntry
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  type: Class
  source:
    remote:
      path: OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: EnumEntry
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
    startLine: 36
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.OnixClient.Settings
  summary: Represents an entry in an enum setting.
  example: []
  syntax:
    content: public class OnixSettingEnum.EnumEntry
    content.vb: Public Class OnixSettingEnum.EnumEntry
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value
  commentId: P:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value
  id: Value
  parent: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: OnixSettingEnum.EnumEntry.Value
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value
  type: Property
  source:
    remote:
      path: OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: Value
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
    startLine: 40
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.OnixClient.Settings
  summary: The actual value of this enum entry.
  example: []
  syntax:
    content: >-
      [JsonPropertyName("value")]

      public int Value { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <JsonPropertyName("value")>

      Public ReadOnly Property Value As Integer
  overload: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: value
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name
  commentId: P:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name
  id: Name
  parent: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: OnixSettingEnum.EnumEntry.Name
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name
  type: Property
  source:
    remote:
      path: OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: Name
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
    startLine: 45
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.OnixClient.Settings
  summary: The name for this enum entry's value.
  example: []
  syntax:
    content: >-
      [JsonPropertyName("name")]

      public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("name")>

      Public ReadOnly Property Name As String
  overload: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: name
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.#ctor(System.Int32,System.String)
  commentId: M:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.#ctor(System.Int32,System.String)
  id: '#ctor(System.Int32,System.String)'
  parent: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  langs:
  - csharp
  - vb
  name: EnumEntry(int, string)
  nameWithType: OnixSettingEnum.EnumEntry.EnumEntry(int, string)
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.EnumEntry(int, string)
  type: Constructor
  source:
    remote:
      path: OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: .ctor
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
    startLine: 53
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.OnixClient.Settings
  summary: Creates a new enum entry.
  example: []
  syntax:
    content: public EnumEntry(int value, string name)
    parameters:
    - id: value
      type: System.Int32
      description: The value for the entry.
    - id: name
      type: System.String
      description: The name of the value for this entry.
    content.vb: Public Sub New(value As Integer, name As String)
  overload: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.#ctor*
  nameWithType.vb: OnixSettingEnum.EnumEntry.New(Integer, String)
  fullName.vb: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.New(Integer, String)
  name.vb: New(Integer, String)
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As``1
  commentId: M:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As``1
  id: As``1
  parent: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  langs:
  - csharp
  - vb
  name: As<T>()
  nameWithType: OnixSettingEnum.EnumEntry.As<T>()
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As<T>()
  type: Method
  source:
    remote:
      path: OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: As
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Api/OnixClient/Settings/OnixSettingEnum.cs
    startLine: 63
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Api.OnixClient.Settings
  summary: Convenience function to convert this enum entry's value to a specific C# enum type.
  example: []
  syntax:
    content: 'public T As<T>() where T : Enum'
    typeParameters:
    - id: T
      description: The type of the C# Enum.
    return:
      type: '{T}'
      description: The value as that enum
    content.vb: Public Function [As](Of T As [Enum])() As T
  overload: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As*
  nameWithType.vb: OnixSettingEnum.EnumEntry.As(Of T)()
  fullName.vb: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As(Of T)()
  name.vb: As(Of T)()
references:
- uid: OnixRuntime.Api.OnixClient.Settings
  commentId: N:OnixRuntime.Api.OnixClient.Settings
  href: OnixRuntime.html
  name: OnixRuntime.Api.OnixClient.Settings
  nameWithType: OnixRuntime.Api.OnixClient.Settings
  fullName: OnixRuntime.Api.OnixClient.Settings
  spec.csharp:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Api
    name: Api
    href: OnixRuntime.Api.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient
    name: OnixClient
    href: OnixRuntime.Api.OnixClient.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings
    name: Settings
    href: OnixRuntime.Api.OnixClient.Settings.html
  spec.vb:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Api
    name: Api
    href: OnixRuntime.Api.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient
    name: OnixClient
    href: OnixRuntime.Api.OnixClient.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings
    name: Settings
    href: OnixRuntime.Api.OnixClient.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value*
  commentId: Overload:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.html#OnixRuntime_Api_OnixClient_Settings_OnixSettingEnum_EnumEntry_Value
  name: Value
  nameWithType: OnixSettingEnum.EnumEntry.Value
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Value
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name*
  commentId: Overload:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.html#OnixRuntime_Api_OnixClient_Settings_OnixSettingEnum_EnumEntry_Name
  name: Name
  nameWithType: OnixSettingEnum.EnumEntry.Name
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.#ctor*
  commentId: Overload:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.#ctor
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.html#OnixRuntime_Api_OnixClient_Settings_OnixSettingEnum_EnumEntry__ctor_System_Int32_System_String_
  name: EnumEntry
  nameWithType: OnixSettingEnum.EnumEntry.EnumEntry
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.EnumEntry
  nameWithType.vb: OnixSettingEnum.EnumEntry.New
  fullName.vb: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.New
  name.vb: New
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As*
  commentId: Overload:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.html#OnixRuntime_Api_OnixClient_Settings_OnixSettingEnum_EnumEntry_As__1
  name: As
  nameWithType: OnixSettingEnum.EnumEntry.As
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.As
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
