### YamlMime:ManagedReference
items:
- uid: OnixRuntime.Api.OnixClient.Settings
  commentId: N:OnixRuntime.Api.OnixClient.Settings
  id: OnixRuntime.Api.OnixClient.Settings
  children:
  - OnixRuntime.Api.OnixClient.Settings.InvalidOnixEnumValueException
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingAir
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingBool
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingButton
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingCategory
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeConverter
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeMutableConverter
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingCustom
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingFloat
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingInfo
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingInt
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingKeybind
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingLocalizedInfo
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingModuleHeader
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingTextbox
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingValueAdapterEnum
  - OnixRuntime.Api.OnixClient.Settings.OnixSettingVec2
  langs:
  - csharp
  - vb
  name: OnixRuntime.Api.OnixClient.Settings
  nameWithType: OnixRuntime.Api.OnixClient.Settings
  fullName: OnixRuntime.Api.OnixClient.Settings
  type: Namespace
  assemblies:
  - OnixRuntime
references:
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingAir
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingAir
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingAir.html
  name: OnixSettingAir
  nameWithType: OnixSettingAir
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingAir
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingBool
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingBool
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingBool.html
  name: OnixSettingBool
  nameWithType: OnixSettingBool
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingBool
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingButton
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingButton
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingButton.html
  name: OnixSettingButton
  nameWithType: OnixSettingButton
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingButton
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingCategory
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingCategory
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingCategory.html
  name: OnixSettingCategory
  nameWithType: OnixSettingCategory
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingCategory
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  name: OnixSettingColor
  nameWithType: OnixSettingColor
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType
  parent: OnixRuntime.Api.OnixClient.Settings
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  name: OnixSettingColor.ValueType
  nameWithType: OnixSettingColor.ValueType
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType
  spec.csharp:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
    name: OnixSettingColor
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType
    name: ValueType
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType.html
  spec.vb:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
    name: OnixSettingColor
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType
    name: ValueType
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueType.html
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable
  parent: OnixRuntime.Api.OnixClient.Settings
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  name: OnixSettingColor.ValueTypeMutable
  nameWithType: OnixSettingColor.ValueTypeMutable
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable
  spec.csharp:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
    name: OnixSettingColor
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable
    name: ValueTypeMutable
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable.html
  spec.vb:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor
    name: OnixSettingColor
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable
    name: ValueTypeMutable
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor.ValueTypeMutable.html
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeMutableConverter
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeMutableConverter
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeMutableConverter.html
  name: OnixSettingColor_ValueTypeMutableConverter
  nameWithType: OnixSettingColor_ValueTypeMutableConverter
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeMutableConverter
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeConverter
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeConverter
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeConverter.html
  name: OnixSettingColor_ValueTypeConverter
  nameWithType: OnixSettingColor_ValueTypeConverter
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingColor_ValueTypeConverter
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingCustom
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingCustom
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingCustom.html
  name: OnixSettingCustom
  nameWithType: OnixSettingCustom
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingCustom
- uid: OnixRuntime.Api.OnixClient.Settings.InvalidOnixEnumValueException
  commentId: T:OnixRuntime.Api.OnixClient.Settings.InvalidOnixEnumValueException
  href: OnixRuntime.Api.OnixClient.Settings.InvalidOnixEnumValueException.html
  name: InvalidOnixEnumValueException
  nameWithType: InvalidOnixEnumValueException
  fullName: OnixRuntime.Api.OnixClient.Settings.InvalidOnixEnumValueException
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  name: OnixSettingEnum
  nameWithType: OnixSettingEnum
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  name: OnixSettingEnum.EnumEntry
  nameWithType: OnixSettingEnum.EnumEntry
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
  spec.csharp:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
    name: OnixSettingEnum
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
    name: EnumEntry
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.html
  spec.vb:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
    name: OnixSettingEnum
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry
    name: EnumEntry
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntry.html
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries
  parent: OnixRuntime.Api.OnixClient.Settings
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  name: OnixSettingEnum.EnumEntries
  nameWithType: OnixSettingEnum.EnumEntries
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries
  spec.csharp:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
    name: OnixSettingEnum
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries
    name: EnumEntries
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries.html
  spec.vb:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum
    name: OnixSettingEnum
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries
    name: EnumEntries
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingEnum.EnumEntries.html
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingValueAdapterEnum
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingValueAdapterEnum
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingValueAdapterEnum.html
  name: OnixSettingValueAdapterEnum
  nameWithType: OnixSettingValueAdapterEnum
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingValueAdapterEnum
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingFloat
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingFloat
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingFloat.html
  name: OnixSettingFloat
  nameWithType: OnixSettingFloat
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingFloat
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.html
  name: OnixSettingGamepadKeybind
  nameWithType: OnixSettingGamepadKeybind
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType
  parent: OnixRuntime.Api.OnixClient.Settings
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.html
  name: OnixSettingGamepadKeybind.ValueType
  nameWithType: OnixSettingGamepadKeybind.ValueType
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType
  spec.csharp:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind
    name: OnixSettingGamepadKeybind
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType
    name: ValueType
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType.html
  spec.vb:
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind
    name: OnixSettingGamepadKeybind
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType
    name: ValueType
    href: OnixRuntime.Api.OnixClient.Settings.OnixSettingGamepadKeybind.ValueType.html
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingInfo
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingInfo
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingInfo.html
  name: OnixSettingInfo
  nameWithType: OnixSettingInfo
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingInfo
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingLocalizedInfo
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingLocalizedInfo
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingLocalizedInfo.html
  name: OnixSettingLocalizedInfo
  nameWithType: OnixSettingLocalizedInfo
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingLocalizedInfo
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingModuleHeader
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingModuleHeader
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingModuleHeader.html
  name: OnixSettingModuleHeader
  nameWithType: OnixSettingModuleHeader
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingModuleHeader
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingInt
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingInt
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingInt.html
  name: OnixSettingInt
  nameWithType: OnixSettingInt
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingInt
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingKeybind
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingKeybind
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingKeybind.html
  name: OnixSettingKeybind
  nameWithType: OnixSettingKeybind
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingKeybind
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingTextbox
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingTextbox
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingTextbox.html
  name: OnixSettingTextbox
  nameWithType: OnixSettingTextbox
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingTextbox
- uid: OnixRuntime.Api.OnixClient.Settings.OnixSettingVec2
  commentId: T:OnixRuntime.Api.OnixClient.Settings.OnixSettingVec2
  href: OnixRuntime.Api.OnixClient.Settings.OnixSettingVec2.html
  name: OnixSettingVec2
  nameWithType: OnixSettingVec2
  fullName: OnixRuntime.Api.OnixClient.Settings.OnixSettingVec2
- uid: OnixRuntime.Api.OnixClient.Settings
  commentId: N:OnixRuntime.Api.OnixClient.Settings
  href: OnixRuntime.html
  name: OnixRuntime.Api.OnixClient.Settings
  nameWithType: OnixRuntime.Api.OnixClient.Settings
  fullName: OnixRuntime.Api.OnixClient.Settings
  spec.csharp:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Api
    name: Api
    href: OnixRuntime.Api.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient
    name: OnixClient
    href: OnixRuntime.Api.OnixClient.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings
    name: Settings
    href: OnixRuntime.Api.OnixClient.Settings.html
  spec.vb:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Api
    name: Api
    href: OnixRuntime.Api.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient
    name: OnixClient
    href: OnixRuntime.Api.OnixClient.html
  - name: .
  - uid: OnixRuntime.Api.OnixClient.Settings
    name: Settings
    href: OnixRuntime.Api.OnixClient.Settings.html
