### YamlMime:ManagedReference
items:
- uid: OnixRuntime.Plugin.OnixPluginSaveManager.OnConfigSaveDelegate
  commentId: T:OnixRuntime.Plugin.OnixPluginSaveManager.OnConfigSaveDelegate
  id: OnixPluginSaveManager.OnConfigSaveDelegate
  parent: OnixRuntime.Plugin
  children: []
  langs:
  - csharp
  - vb
  name: OnixPluginSaveManager.OnConfigSaveDelegate
  nameWithType: OnixPluginSaveManager.OnConfigSaveDelegate
  fullName: OnixRuntime.Plugin.OnixPluginSaveManager.OnConfigSaveDelegate
  type: Delegate
  source:
    remote:
      path: OnixRuntime/Plugin/OnixPluginSaveManager.cs
      branch: master
      repo: https://github.com/OnixClient/OnixDotnetRuntime
    id: OnConfigSaveDelegate
    path: ../../../../../../../Users/jqms/source/repos/OnixDotnetRuntime/OnixRuntime/Plugin/OnixPluginSaveManager.cs
    startLine: 127
  assemblies:
  - OnixRuntime
  namespace: OnixRuntime.Plugin
  syntax:
    content: public delegate JsonNode? OnixPluginSaveManager.OnConfigSaveDelegate()
    return:
      type: System.Text.Json.Nodes.JsonNode
    content.vb: Public Delegate Function OnixPluginSaveManager.OnConfigSaveDelegate() As JsonNode
references:
- uid: OnixRuntime.Plugin
  commentId: N:OnixRuntime.Plugin
  href: OnixRuntime.html
  name: OnixRuntime.Plugin
  nameWithType: OnixRuntime.Plugin
  fullName: OnixRuntime.Plugin
  spec.csharp:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Plugin
    name: Plugin
    href: OnixRuntime.Plugin.html
  spec.vb:
  - uid: OnixRuntime
    name: OnixRuntime
    href: OnixRuntime.html
  - name: .
  - uid: OnixRuntime.Plugin
    name: Plugin
    href: OnixRuntime.Plugin.html
- uid: System.Text.Json.Nodes.JsonNode
  commentId: T:System.Text.Json.Nodes.JsonNode
  parent: System.Text.Json.Nodes
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.text.json.nodes.jsonnode
  name: JsonNode
  nameWithType: JsonNode
  fullName: System.Text.Json.Nodes.JsonNode
- uid: System.Text.Json.Nodes
  commentId: N:System.Text.Json.Nodes
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Text.Json.Nodes
  nameWithType: System.Text.Json.Nodes
  fullName: System.Text.Json.Nodes
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Text
    name: Text
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.text
  - name: .
  - uid: System.Text.Json
    name: Json
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.text.json
  - name: .
  - uid: System.Text.Json.Nodes
    name: Nodes
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.text.json.nodes
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Text
    name: Text
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.text
  - name: .
  - uid: System.Text.Json
    name: Json
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.text.json
  - name: .
  - uid: System.Text.Json.Nodes
    name: Nodes
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.text.json.nodes
