name: Generate Docs

on:
  push:
    paths:
      - 'docs/**'
      - 'guide/**'
      - 'images/**'
      - 'docfx.json'
      - 'index.md'
      - 'toc.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs Repo (public)
        uses: actions/checkout@v3
        with:
          repository: OnixClient-Plugins/OnixRuntimeDocs
          path: OnixRuntimeDocs

      - name: Checkout Runtime Repo (private)
        uses: actions/checkout@v3
        with:
          repository: OnixClient-Plugins/OnixRuntime
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: OnixRuntime

      - name: Setup DocFX
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-7.0
          dotnet tool install -g docfx-cli
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run DocFX Build
        working-directory: OnixRuntimeDocs
        run: docfx docfx.json

      - name: Commit and Push _site
        working-directory: OnixRuntimeDocs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/OnixClient-Plugins/OnixRuntimeDocs.git
          git add _site
          git commit -m "auto: update _site from docfx build" || echo "No changes to commit"
          git push origin main
