name: Generate Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'guide/**'
      - 'images/**'
      - 'docfx.json'
      - 'index.md'
      - 'toc.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone private repo (OnixRuntime)
        env:
          PAT: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git clone https://$PAT@github.com/OnixClient-Plugins/OnixRuntime.git ../OnixRuntime

      - name: Update docfx.json src path
        run: |
          sed -i 's|C:\\\\Users\\\\jqms\\\\source\\\\repos\\\\OnixDotnetRuntime|../OnixRuntime|' docfx.json

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Add DocFX to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run DocFX
        run: docfx docfx.json

      - name: Commit and push _site
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'auto: update _site from docfx build'
          file_pattern: '_site/**'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
