name: Generate Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'guide/**'
      - 'images/**'
      - 'docfx.json'
      - 'index.md'
      - 'toc.yml'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo (OnixRuntimeDocs)
        uses: actions/checkout@v3

      - name: Clone private repo (OnixRuntime)
        env:
          PAT: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git clone https://$PAT@github.com/OnixClient-Plugins/OnixRuntime.git ../OnixRuntime

      - name: Update docfx.json src path
        run: |
          sed -i 's|C:\\\\Users\\\\jqms\\\\source\\\\repos\\\\OnixDotnetRuntime|../OnixRuntime|' docfx.json

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Add DocFX to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run DocFX
        run: docfx docfx.json

      - name: Commit and push _site to public repo
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _site
          git commit -m "auto: update _site from docfx build" || echo "No changes to commit"
          git pull --rebase "https://x-access-token:${PERSONAL_TOKEN}@github.com/OnixClient-Plugins/OnixRuntimeDocs.git" main
          git push "https://x-access-token:${PERSONAL_TOKEN}@github.com/OnixClient-Plugins/OnixRuntimeDocs.git" HEAD:main
